### ISSUE TITLE
MiBPHP Fatal error:  Class 'GuzzleHttp\Command\Guzzle\GuzzleClient' not found

### ISSUE THREAD

**Issue by pjayramkumar** [keenlabs/KeenClient-PHP#137]
While install the Keenio in Magento 2 we are missing the dependance library there

**Comment by piotrek-buchman** [comment]
Hello @pjayramkumar 

Thank you for reporting the issue. Unfortunately the information you shared is not sufficient to provide you with any kind of advice. Please share the following environment details:

- operating system 
- version of PHP 
- version of Keen SDK
- specific version of Magento (2.3? 2.2?)
- what command do you execute when it fails?
- if you use composer - what is its version? what is the content of composer schema file?

**Comment by pjayramkumar** [comment]
Hello

operating system : 

PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

______________________________

version of PHP : 

PHP 7.2.14-1+0~20190113100657.14+jessie~1.gbpd83c69 (cli) (built: Jan 13 2019 10:30:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.2.0, Copyright (c) 2002-2018, by ionCube Ltd.
    with Zend OPcache v7.2.14-1+0~20190113100657.14+jessie~1.gbpd83c69, Copyright (c) 1999-2018, by Zend Technologies


________________________________________

version of Keen SDK : 

"require": {
        "keen-io/keen-io":"~2.5"
    },

________________________________________

specific version of Magento : 

Magento CLI 2.3.0
________________________________________

what command do you execute when it fails? : 

php bin/magento setup:di:compile

________________________________________

if you use composer - what is its version? what is the content of composer schema file?

Version : Composer version 1.8.4 2019-02-11 10:52:10

{
    "name": "xyz/module-keenio",
    "description": "",
    "type": "magento2-module",
    "license": "OSL-3.0",
    "authors": [
        {
            "email": "support@xyz.io",
            "name": "xyz"
        }
    ],
    "minimum-stability": "dev",
    "require": {
        "keen-io/keen-io":"~2.5"
    },
    "autoload": {
        "files": [
            "registration.php",
            "vendor/autoload.php"
        ],
        "psr-4": {
            "xyz\\Keenio\\": ""
        }
    }
}

**Comment by piotrek-buchman** [comment]
Have you run first the composer in order to download the Keen SDK dependency?

**Comment by pjayramkumar** [comment]
Hello 

I have download the keen SDK dependency via composer 

here is steps

step1 :

i have added the keen-io in the require section of the composer then i run composer update 

so it download all the dependance of it 


output


Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 9 installs, 0 updates, 0 removals
  - Installing paragonie/random_compat (v2.0.18): Loading from cache
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing psr/http-message (dev-master f6561bf): Cloning f6561bf28d
  - Installing guzzlehttp/psr7 (dev-master a346647): Cloning a346647434
  - Installing guzzlehttp/promises (dev-master 926eaa3): Cloning 926eaa3ff7
  - Installing guzzlehttp/guzzle (dev-master fa74540): Cloning fa745406c2
  - Installing guzzlehttp/command (1.0.0): Loading from cache
  - Installing guzzlehttp/guzzle-services (1.1.3): Loading from cache
  - Installing keen-io/keen-io (2.6.0): Loading from cache
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
guzzlehttp/psr7 suggests installing zendframework/zend-httphandlerrunner (Emit PSR-7 responses)
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
guzzlehttp/guzzle-services suggests installing gimler/guzzle-description-loader (^0.0.4)
Writing lock file
Generating autoload files

**Comment by piotrek-buchman** [comment]
Hello @pjayramkumar 

I've spent some time trying to reproduce this issue but I failed. An error you get seem to be strictly related to the way you've set up Magento and without looking into the details of your code I'm not able to provide you with any additional assistance. 

What I'd suggest is trying to install Magento with composer and then adding Keen SDK dependency.

I can make an additional effort to help you, but I have to make sure that both your and mine environments are exactly the same. In order to do that, please share a git repository with your project setup, including a Dockerfile that sets up environment and all dependencies. You can find base docker images [here](https://hub.docker.com/_/php).

**Comment by pjayramkumar** [comment]
Hello

i have mangeto on cloudways server , so i can't share with you 

i get the error when i fire this command

php bin/magento setup:di:compile


can you share your screenshot where you are doing so i know what to do ?

**Comment by piotrek-buchman** [comment]
Hello again,

I've setup a docker container (Debian jessie) with PHP 7 installed, then managed to install composer , create `compose.json` and run `php composer.phar update` which succeeded (very similar output to what you have provided). I didn't notice dependency on Magento in your `composer.json` file so that I decided to download a zip file from Magento GitHub page, but I failed to reproduce this issue. As you mentioned you decided to use managed solution provided by Cloudways so your setup is quite different. Your issue seems to be more related to Magento installation than to our library itself. Taking into consideration all above I won't be able to help you. This would be a custom work and is out of the scope of support that we provide to our customers.

**Comment by pjayramkumar** [comment]
Hello,

i found the solution

issue is : guzzle library is already in build in magento 2 and keen-io also use while we install that as per module vendor folder via composer

so library get duplicate one in global vendor folder and one in module vendor folder 

i have installed directly in the global cendor folder and it works for me
